CC = gcc
CFLAGS = -g -Wall -pedantic -std=gnu99
TARGETS = unique_string permutation

.DEFAULT: all

all: $(TARGETS)

unique_string: unique_string.c
		$(CC) $(CFLAGS) unique_string.c -o unique_string

permutation: permutation.c
		$(CC) $(CFLAGS) permutation.c -o permutation
